# Generated by Django 5.0.2 on 2024-03-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dietetica', '0003_remove_clientes_direccion_alter_clientes_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productos_pormayor',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
