# Generated by Django 5.0.2 on 2024-03-11 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dietetica', '0004_alter_productos_precio_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos_pormayor',
            new_name='ProductosPorMayor',
        ),
    ]
